var exp_opg = {
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "name": "OPG Marin Bušljeta", "photo": "marbusljeta", "addr": "Kruškovac BB, Starigrad-Paklenica", "prod": "jaja, sir, kozje mlijeko, meso jaradi", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.43615, 44.30142 ] } },
{ "type": "Feature", "properties": { "name": "OPG Marijan Bušljeta", "photo": "mbusljeta", "addr": "Jose Dokoze 51, Starigrad-Paklenica", "prod": "med", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.43383, 44.29829 ] } },
{ "type": "Feature", "properties": { "name": "OPG Franjo Špalj", "photo": "fspalj", "addr": "Petra Zoranića 29, Starigrad-Paklenica", "prod": "med", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.44706, 44.29097 ] } },
{ "type": "Feature", "properties": { "name": "OPG Marijana Knežević", "photo": "mknezevic", "addr": "Seline, Kneževići 1, Libinje", "prod": "rakije, likeri, med, jaja", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.54454, 44.29448 ] } },
{ "type": "Feature", "properties": { "name": "OPG Ivica Krapić", "photo": "ikrapic", "addr": "Lađen Porat 7, Starigrad-Paklenica", "prod": "med, propolis", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.39818, 44.32209 ] } },
{ "type": "Feature", "properties": { "name": "Sirana Runolist", "photo": null, "addr": null, "prod": null, "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.0594, 44.82031 ] } },
{ "type": "Feature", "properties": { "name": "OPG Anić", "photo": null, "addr": "Anići 54, Krasno", "prod": "mlijeko, sir, mliječni proizvodi", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.04641, 44.82163 ] } },
{ "type": "Feature", "properties": { "name": "OPG Ivan Vlainić", "photo": "ivlainic", "addr": "Prvan Selo 50, Perušić", "prod": "rakije", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.39399, 44.62691 ] } },
{ "type": "Feature", "properties": { "name": "OPG Ivanka Turić", "photo": "ituric", "addr": "Varoš 22, Perušić", "prod": "džemovi, kompoti, prirodni sokovi, likeri, kiselo zelje, konzervirano povrće (paprika, turšija, krastavci…), med, mesne prerađevine, jaja", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.38224, 44.66566 ] } },
{ "type": "Feature", "properties": { "name": "OPG Josip Žarak", "photo": "jzarak", "addr": "Stjepana Radića 31, Perušić", "prod": "prirodni sokovi, ukrasne krpene lutkice", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.38182, 44.65252 ] } },
{ "type": "Feature", "properties": { "name": "OPG Ljiljana Crnković", "photo": "lcrnkovic", "addr": "Pod Kunjačom 3, Perušić", "prod": "med, propolis, med u saću, svijeće od pčelinjeg voska", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.37803, 44.65501 ] } },
{ "type": "Feature", "properties": { "name": "OPG Marija Žarak", "photo": "mzarak", "addr": "Stjepana Radića 72, Perušić", "prod": "džemovi, kompoti, prirodni sokovi, rakije, likeri, kiselo zelje, mesne prerađevine, jaja, sir, basa - lički ovčji sir", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.37887, 44.65186 ] } },
{ "type": "Feature", "properties": { "name": "OPG Nada Murgić", "photo": "nmurgic", "addr": "Kralja Tomislava 6, Perušić", "prod": "jaja, mlijeko, sir", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.38439, 44.65027 ] } },
{ "type": "Feature", "properties": { "name": "OPG Nikolina Hećimović", "photo": "hecimovic", "addr": "Kaniža 86, Perušić", "prod": "džemovi", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.36646, 44.65162 ] } },
{ "type": "Feature", "properties": { "name": "OPG Vesnica Kasumović", "photo": "kasunovic", "addr": "Kvarte 106, Perušić", "prod": "med, propolis, svijeće od pčelinjeg voska, cvjetni prah, krumpir", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.38125, 44.68797 ] } },
{ "type": "Feature", "properties": { "name": "OPG Vlado Orešković", "photo": "oreskovic", "addr": "Kralja Zvonimira 5a, Perušić", "prod": "med", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.37833, 44.64739 ] } },
{ "type": "Feature", "properties": { "name": "OPG Brkić", "photo": null, "addr": "Krasno 97a", "prod": "džemovi, prirodni sokovi, med, ljekovito i začinsko bilje", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.05968, 44.81715 ] } },
{ "type": "Feature", "properties": { "name": "OPG Lulić", "photo": "lulic", "addr": "Pajinovići 97, Krasno", "prod": "džemovi, kompoti, prirodni sokovi, kiselo zelje, konzervirano povrće, mesne prerađevne, jaja, ljekovito i začinsko bilje", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.05979, 44.81717 ] } },
{ "type": "Feature", "properties": { "name": "OPG Anka Nenadić", "photo": "anenadic", "addr": "Kvarte 47, Perušić", "prod": "džemovi, kompoti, prirodni sokovi, rakije, likeri, kiselo zelje, konzervirano povrće (paprika, ajvar, krastavci), mesne prerađevine, brašno (pšenica, raž)", "photo2": "fspalj" }, "geometry": { "type": "Point", "coordinates": [ 15.38322, 44.67895 ] } }
]
}
